"""First Migration

Revision ID: 246b028add52
Revises: 
Create Date: 2020-06-05 23:42:31.263160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246b028add52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('state_of_origin', sa.String(length=64), nullable=True),
    sa.Column('local_govt', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('reason_for_donating', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_sponsors_address'), 'sponsors', ['address'], unique=False)
    op.create_index(op.f('ix_sponsors_email'), 'sponsors', ['email'], unique=True)
    op.create_index(op.f('ix_sponsors_firstname'), 'sponsors', ['firstname'], unique=False)
    op.create_index(op.f('ix_sponsors_lastname'), 'sponsors', ['lastname'], unique=False)
    op.create_index(op.f('ix_sponsors_local_govt'), 'sponsors', ['local_govt'], unique=False)
    op.create_index(op.f('ix_sponsors_reason_for_donating'), 'sponsors', ['reason_for_donating'], unique=False)
    op.create_index(op.f('ix_sponsors_state_of_origin'), 'sponsors', ['state_of_origin'], unique=False)
    op.create_index(op.f('ix_sponsors_username'), 'sponsors', ['username'], unique=True)
    op.create_table('statuss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('youths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('state_of_origin', sa.String(length=64), nullable=True),
    sa.Column('local_govt', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('education_level', sa.String(length=64), nullable=True),
    sa.Column('reason_for_applying', sa.Text(), nullable=True),
    sa.Column('bvn', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuss.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_youths_address'), 'youths', ['address'], unique=False)
    op.create_index(op.f('ix_youths_bvn'), 'youths', ['bvn'], unique=True)
    op.create_index(op.f('ix_youths_education_level'), 'youths', ['education_level'], unique=False)
    op.create_index(op.f('ix_youths_email'), 'youths', ['email'], unique=True)
    op.create_index(op.f('ix_youths_firstname'), 'youths', ['firstname'], unique=False)
    op.create_index(op.f('ix_youths_lastname'), 'youths', ['lastname'], unique=False)
    op.create_index(op.f('ix_youths_local_govt'), 'youths', ['local_govt'], unique=False)
    op.create_index(op.f('ix_youths_reason_for_applying'), 'youths', ['reason_for_applying'], unique=False)
    op.create_index(op.f('ix_youths_state_of_origin'), 'youths', ['state_of_origin'], unique=False)
    op.create_index(op.f('ix_youths_username'), 'youths', ['username'], unique=True)
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youth_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=144), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['youth_id'], ['youths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_post')
    op.drop_index(op.f('ix_youths_username'), table_name='youths')
    op.drop_index(op.f('ix_youths_state_of_origin'), table_name='youths')
    op.drop_index(op.f('ix_youths_reason_for_applying'), table_name='youths')
    op.drop_index(op.f('ix_youths_local_govt'), table_name='youths')
    op.drop_index(op.f('ix_youths_lastname'), table_name='youths')
    op.drop_index(op.f('ix_youths_firstname'), table_name='youths')
    op.drop_index(op.f('ix_youths_email'), table_name='youths')
    op.drop_index(op.f('ix_youths_education_level'), table_name='youths')
    op.drop_index(op.f('ix_youths_bvn'), table_name='youths')
    op.drop_index(op.f('ix_youths_address'), table_name='youths')
    op.drop_table('youths')
    op.drop_table('statuss')
    op.drop_index(op.f('ix_sponsors_username'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_state_of_origin'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_reason_for_donating'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_local_govt'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_lastname'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_firstname'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_email'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_address'), table_name='sponsors')
    op.drop_table('sponsors')
    op.drop_table('projects')
    # ### end Alembic commands ###
